tap "homebrew/cask"

brew "dockutil"
brew "nvm"
brew "npm"
brew "yarn"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pipenv"
brew "fzf"
brew "bat"
brew "neovim"

cask "1password"
cask "appcleaner"
cask "google-chrome"
cask "iterm2"
cask "slack"
cask "spotify"
cask "intellij-idea-ce"
cask "pycharm"
cask "webstorm"
cask "visual-studio-code"
cask "daisydisk"
cask "docker"
cask "dropbox"
cask "bettertouchtool"
