promptToReturnFromSubprocess: false
git:
  autoFetch: false
keybinding:
  universal:
    createPatchOptionsMenu: <c-k>
customCommands:
  - key: 'O'
    context: 'global'
    command: 'charm .'
  - key: "G"
    command: "gh pr view -w {{.SelectedLocalBranch.Name}}"
    context: "localBranches"
    output: log
  - key: "c"
    command: "git push --set-upstream origin {{.SelectedLocalBranch.Name}} && gh c"
    context: "localBranches"
    output: log
